meta_product_name: "Skanfare"
meta_title: "Skanfare - Book Flights at the Right Time"
meta_description: "Skanfare helps you get more value with your money by calculating cheapest routes to different destinations and notify you of signficant discounts"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
